namespace SotnApi.Constants.Values.Game.Enums
{
    public enum Zone
    {
        MarbleGallery = 0,
        OuterWall = 1,
        LongLibrary = 2,
        Catacombs = 3,
        OlroxsQuarters = 4,
        AbandonedMine = 5,
        RoyalChapel = 6,
        CastleEntrance = 7,
        CenterCube = 8,
        UndergroundCaverns = 9,
        Colosseum = 0xA,
        CastleKeep = 0xB,
        AlchemyLaboratory = 0xC,
        ClockTower = 0xD,
        Warp = 0xE,
        Nightmare = 0x12,
        SlograGaibon = 0x13,
        Karasuman = 0x14,
        LesserDemon = 0x15,
        Cerberus = 0x16,
        ClockRoomCutscene = 0x17,
        RichterFight = 0x18,
        Hippogryph = 0x19,
        Doppleganger10 = 0x1A,
        Scylla = 0x1B,
        MinotaurWerewolf = 0x1C,
        Granfaloon = 0x1D,
        Olrox = 0x1E,
        Prologue = 0x1F,
        BlackMarbleGallery = 0x20,
        ReverseOuterWall = 0x21,
        ForbiddenLibrary = 0x22,
        FloatingCatacombs = 0x23,
        DeathWingsLair = 0x24,
        Cave = 0x25, //Inverted Mines
        AntiChapel = 0x26,
        ReverseEntrance = 0x27,
        ReverseCaverns = 0x29,
        ReverseColosseum = 0x2A,
        ReverseCastleKeep = 0x2B,
        NecromancyLaboratory = 0x2C,
        ReverseClockTower = 0x2D,
        ReverseWarp = 0x2E,
        //ThirdOuterWall = 0x2F,
    }
}
