using System.Collections.Generic;

namespace SotnApi.Constants.Values.Alucard
{
    public static class Equipment
    {
        public static readonly List<string> Items = new List<string>
       {
            "empty hand",
            "monster vial 1",
            "monster vial 2",
            "monster vial 3",
            "Shield rod",
            "Leather shield",
            "Knight shield",
            "Iron shield",
            "AxeLord shield",
            "Herald shield",
            "Dark shield",
            "Goddess shield",
            "Shaman shield",
            "Medusa shield",
            "Skull shield",
            "Fire shield",
            "Alucard shield",
            "Sword of Dawn",
            "Basilard",
            "Short sword",
            "Combat knife",
            "Nunchaku",
            "Were Bane",
            "Rapier",
            "Karma Coin",
            "Magic Missile",
            "Red Rust",
            "Takemitsu",
            "Shotel",
            "Orange",
            "Apple",
            "Banana",
            "Grapes",
            "Strawberry",
            "Pineapple",
            "Peanuts",
            "Toadstool",
            "Shiitake",
            "Cheesecake",
            "Shortcake",
            "Tart",
            "Parfait",
            "Pudding",
            "Ice cream",
            "Frankfurter",
            "Hamburger",
            "Pizza",
            "Cheese",
            "Ham and eggs",
            "Omlette",
            "Morning Set",
            "Lunch A",
            "Lunch B",
            "Curry rice",
            "Gyros plate",
            "Spaghetti",
            "Grape juice",
            "Barley tea",
            "Green tea",
            "Natou",
            "Ramen",
            "Miso soup",
            "Sushi",
            "Pork bun",
            "Red bean bun",
            "Chinese bun",
            "Dim Sum set",
            "Pot Roast",
            "Sirloin",
            "Turkey",
            "Meal ticket",
            "Neutron bomb",
            "Power of Sire",
            "Pentagram",
            "Bat Pentagram",
            "Shuriken",
            "Cross shuriken",
            "Buffalo star",
            "Flame star",
            "TNT",
            "Bwaka knife",
            "Boomerang",
            "Javelin",
            "Tyrfing",
            "Namakura",
            "Knuckle duster",
            "Gladius",
            "Scimitar",
            "Cutlass",
            "Saber",
            "Falchion",
            "Broadsword",
            "Bekatowa",
            "Damascus sword",
            "Hunter sword",
            "Estoc",
            "Bastard sword",
            "Jewel knuckles",
            "Claymore",
            "Talwar",
            "Katana",
            "Flamberge",
            "Iron Fist",
            "Zweihander",
            "Sword of Hador",
            "Luminus",
            "Harper",
            "Obsidian sword",
            "Gram",
            "Jewel sword",
            "Mormegil",
            "Firebrand",
            "Thunderbrand",
            "Icebrand",
            "Stone sword",
            "Holy sword",
            "Terminus Est",
            "Marsil",
            "Dark Blade",
            "Heaven sword",
            "Fist of Tulkas",
            "Gurthang",
            "Mourneblade",
            "Alucard sword",
            "Mablung Sword",
            "Badelaire",
            "Sword Familiar",
            "Great Sword",
            "Mace",
            "Morningstar",
            "Holy rod",
            "Star flail",
            "Moon rod",
            "Chakram",
            "Fire boomerang",
            "Iron ball",
            "Holbein dagger",
            "Blue knuckles",
            "Dynamite",
            "Osafune katana",
            "Masamune",
            "Muramasa",
            "Heart Refresh",
            "Runesword",
            "Antivenom",
            "Uncurse",
            "Life apple",
            "Hammer",
            "Str. potion",
            "Luck potion",
            "Smart potion",
            "Attack potion",
            "Shield potion",
            "Resist fire",
            "Resist thunder",
            "Resist ice",
            "Resist stone",
            "Resist holy",
            "Resist dark",
            "Potion",
            "High potion",
            "Elixir",
            "Manna prism",
            "Vorpal blade",
            "Crissaegrim",
            "Yasatsuna",
            "Library card",
            "Alucart shield",
            "Alucart sword",
            "----armor",
            "Cloth tunic",
            "Hide cuirass",
            "Bronze cuirass",
            "Iron cuirass",
            "Steel cuirass",
            "Silver plate",
            "Gold plate",
            "Platinum mail",
            "Diamond plate",
            "Fire mail",
            "Lightning mail",
            "Ice mail",
            "Mirror cuirass",
            "Spike Breaker",
            "Alucard mail",
            "Dark armor",
            "Healing mail",
            "Holy mail",
            "Walk armor",
            "Brilliant mail",
            "Mojo mail",
            "Fury plate",
            "Dracula tunic",
            "God's Garb",
            "Axe Lord armor",
            "----helm",
            "Sunglasses",
            "Ballroom mask",
            "Bandanna",
            "Felt hat",
            "Velvet hat",
            "Goggles",
            "Leather hat",
            "Holy glasses",
            "Steel helm",
            "Stone mask",
            "Circlet",
            "Gold circlet",
            "Ruby circlet",
            "Opal circlet",
            "Topaz circlet",
            "Beryl circlet",
            "Cat-eye circl.",
            "Coral circlet",
            "Dragon helm",
            "Silver crown",
            "Wizard hat",
            "----cloak",
            "Cloth cape",
            "Reverse cloak",
            "Elven cloak",
            "Crystal cloak",
            "Royal cloak",
            "Blood cloak",
            "Joseph's cloak",
            "Twilight cloak",
            "----accessory",
            "Moonstone",
            "Sunstone",
            "Bloodstone",
            "Staroulite",
            "Ring of Pales",
            "Zircon",
            "Aquamarine",
            "Turquoise",
            "Onyx",
            "Garnet",
            "Opal",
            "Diamond",
            "Lapis lazuli",
            "Ring of Ares",
            "Gold Ring",
            "Silver Ring",
            "Ring of Varda",
            "Ring of Arcana",
            "Mystic pendant",
            "Heart broach",
            "Necklace of J",
            "Gauntlet",
            "Ankh of Life",
            "Ring of Feanor",
            "Medal",
            "Talisman",
            "Duplicator",
            "King's stone",
            "Covenant stone",
            "Nauglamir",
            "Secret boots",
            "Alucart mail"
        };
        public static readonly List<string> Relics = new List<string>
        {
        "Soul of Bat",
        "Fire of Bat",
        "Echo of Bat",
        "Force of Echo",
        "Soul of Wolf",
        "Power of Wolf",
        "Skill of Wolf",
        "Form of Mist",
        "Power of Mist",
        "Gas Cloud",
        "Cube of Zoe",
        "Spirit Orb",
        "Gravity Boots",
        "Leap Stone",
        "Holy Symbol",
        "Faerie Scroll",
        "Jewel of Open",
        "Merman Statue",
        "Bat Card",
        "Ghost Card",
        "Faerie Card",
        "Demon Card",
        "Sword Card",
        "Sprite Card",
        "Nose Devil Card",
        "Heart of Vlad",
        "Tooth of Vlad",
        "Rib of Vlad",
        "Ring of Vlad",
        "Eye of Vlad",
        };
        public static readonly int[] CategoryHeaders = new int[] { 0, 169, 195, 217, 226 };
        public const uint HelmStart = 0x1A;
        public const uint CloakStart = 0x30;
        public const uint AccessoryStart = 0x39;
        public const int HandCount = 168;
        public const int HelmCount = 21;
        public const int ArmorCount = 26;
        public const int CloakCount = 8;
        public const int AccessoryCount = 31;
        public const int SubweaponCount = 9;
        public const uint LibraryWarped = 0x78;
    }
}
